services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pricewatch
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: pricewatch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
